--- #YAML:1.0
name: Class-DBI-BaseDSN
version: 1.22
license: perl
distribution_type: module
requires:
  Class::DBI: 0
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Class::DBI::BaseDSN:
    file: lib/Class/DBI/BaseDSN.pm
    version: 1.22
generated_by: Module::Build version 0.20
